FROM wordpress:php7.3-apache

COPY --chown=www-data:www-data .wp/wp-content/themes/understrap /var/www/html/wp-content/themes/understrap/
COPY --chown=www-data:www-data .wp/wp-content/themes/fb-diversity /var/www/html/wp-content/themes/fb-diversity/
COPY --chown=www-data:www-data .wp/wp-content/plugins/fb-diversity /var/www/html/wp-content/plugins/fb-diversity/
